version: '3.8'
services:
  app:
    build: .
    container_name: lowlink-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    # Documentation: Mounts code for hot-reloading in dev

  redis:
    image: redis:7-alpine
    container_name: lowlink-redis-dev
    ports:
      - '6379:6379'
    # Documentation: Local Redis for caching, rate limiting, analytics 