version: '3.8'
services:
  app:
    build: .
    container_name: lowlink-app-prod
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - redis
    command: npm run start
    # Documentation: Runs production build for live deployment

  redis:
    image: redis:7-alpine
    container_name: lowlink-redis-prod
    ports:
      - '6379:6379'
    # Documentation: Production Redis instance 